CREATE TABLE IF NOT EXISTS `soa` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `sys_userid` int NOT NULL,
  `sys_groupid` int NOT NULL,
  `user_id` int DEFAULT '0',
  `sys_perm_user` varchar(5) NOT NULL,
  `sys_perm_group` varchar(5) NOT NULL,
  `sys_perm_other` varchar(5) NOT NULL,
  `origin` char(255) NOT NULL,
  `ns` char(255) NOT NULL,
  `mbox` char(255) NOT NULL,
  `serial` int unsigned NOT NULL DEFAULT '1',
  `refresh` int unsigned NOT NULL DEFAULT '28800',
  `retry` int unsigned NOT NULL DEFAULT '7200',
  `expire` int unsigned NOT NULL DEFAULT '604800',
  `minimum` int unsigned NOT NULL DEFAULT '86400',
  `ttl` int unsigned NOT NULL DEFAULT '86400',
  `active` enum('Y','N') NOT NULL,
  `xfer` char(255) NOT NULL,
  `lastmodified` varchar(15) DEFAULT '',
  `pass` int DEFAULT '100',
  `update_acl` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `origin` (`origin`),
  KEY `active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
